version: 2

jobs:
  build:
    docker:
      - image: circleci/node:7.10
      - image: 'postgres:9.6-alpine'
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ''
          PROJECT_ID: edms-api
          CLUSTER_NAME: edms
          CLOUDSDK_COMPUTE_ZONE: us-central1-a
          DEPLOYMENT_NAME: edms-api
          CONTAINER_NAME: edms-api
          DOCKER_PROJECT_NAME: ci
          IMAGE: edms
          IMG_TAG: 0.0.1
          PROJECT_NAME: edms-api
          DEPLOYMENT_ENVIRONMENT: staging
          

    working_directory: ~/workspace

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install Node Packages
          command: |
            yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Running Tests
          command: npm test
      
      - deploy:
          name: Deploy Application
          command: |
            sudo chmod -R 777 ./deployment.sh
            if [ "${CIRCLE_BRANCH}" == "master" ] || [ "${CIRCLE_BRANCH}" == "develop" ]; then
              ./deployment.sh
            fi

