# Javascript Node CircleCI 2.0 configuration file

version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7
      - image: 'postgres:9.6-alpine'
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ''
  
  machine:
    node:
      version: stable

    working_directory: ~/workspace

    steps:
      - checkout

      # # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "package.json" }}
      #     - v1-dependencies-

      # - run: yarn install
      - run:
          name: Install Packages
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Running Tests
          command: npm test
